#!/usr/bin/env bash

# Install command-line tools using Homebrew.

# Make sure we’re using the latest Homebrew.
brew update
brew upgrade

# Install GNU core utilities (those that come with macOS are outdated).
# Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
brew install coreutils

# Install some other useful utilities like `sponge`.
brew install moreutils

# Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed.
brew install findutils

# Install GNU `sed`, overwriting the built-in `sed`.
brew install gnu-sed

# Install `wget` with IRI support.
brew install wget

# Install more recent versions of some macOS tools.
brew install grep
brew install ripgrep
brew install openssh
brew install screen

# Install other useful binaries.
brew install rtk
brew install tmux
brew install bat
brew install fd
brew install delta
brew install eza
brew install fzf
brew install git
brew install go
brew install htop
brew install hub
brew install neovim
brew install tldr
brew install yarn
brew install zoxide
brew install gum
brew install television

brew install zsh-syntax-highlighting
echo 'source "$HOMEBREW_PREFIX/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"' >> "$HOME/.zshrc"

# Quicklook plugins
brew install --cask qlmarkdown
brew install --cask qlvideo
brew install --cask quicklook-csv
brew install --cask quicklook-json
brew install --cask webpquicklook

# Applications
brew install --cask spotify
brew install --cask visual-studio-code
brew install --cask zoomus
brew install --cask google-chrome
brew install --cask kitty
brew install --cask docker
brew install --cask dropbox
brew install --cask betterzipql
brew install --cask claude-code

# post install steps
$(brew --prefix)/opt/fzf/install # To install useful key bindings and fuzzy completion:

# allow quicklook plugins to work on newer macos versions
sudo xattr -cr ~/Library/QuickLook/*.qlgenerator


# Remove outdated versions from the cellar.
brew cleanup
