#!/usr/bin/env bash

# Install command-line tools using Homebrew.

# Make sure we’re using the latest Homebrew.
brew update

# Upgrade any already-installed formulae.
brew upgrade

# Install GNU core utilities (those that come with macOS are outdated).
# Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
brew install coreutils

# Install some other useful utilities like `sponge`.
brew install moreutils

# Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed.
brew install findutils

# Install GNU `sed`, overwriting the built-in `sed`.
brew install gnu-sed --with-default-names

# Install `wget` with IRI support.
brew install wget --with-iri

# Install more recent versions of some macOS tools.
brew install vim --with-override-system-vi
brew install grep
brew install ripgrep
brew install openssh
brew install screen

# Install other useful binaries.
brew install ack
brew install tmux
brew install bat
brew install docker
brew install diff-so-fancy
brew install exa
brew install fzf
brew install git
brew install git-lfs
brew install go
brew install heroku
brew install htop
brew install httpie
brew install hub
brew install imagemagick
brew install neovim
brew install nvm
brew install noti
brew install openconnect
brew install openssl
brew install postgresql
brew install pyenv
brew install pyenv-virtualenv
brew install readline
brew install redis
brew install tldr
brew install tree
brew install watchman
brew install xz
brew install yarn
brew install z

brew install zsh-syntax-highlighting
echo "source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" >> "$HOME/.zshrc"


# install casks (desktop applications)
brew cask install alfred
brew cask install bartender
brew cask install betterzipql
brew cask install docker
brew cask install dropbox
brew cask install firefox

# Fonts
brew tap homebrew/cask-fonts
brew cask install font-fira-code
brew cask install font-hack-nerd-font

brew cask install google-chrome
brew cask install iterm2
brew cask install alacritty
brew cask install vimr
brew cask install ngrok
brew cask install postman
brew cask install psequel
brew cask install qlcolorcode
brew cask install qlimagesize
brew cask install qlmarkdown
brew cask install qlstephen
brew cask install qlvideo
brew cask install quicklook-csv
brew cask install quicklook-json
brew cask install quicklookase
brew cask install react-native-debugger
brew cask install slack
brew cask install spectacle
brew cask install spotify
brew cask install suspicious-package
brew cask install visual-studio-code
brew cask install webpquicklook
brew cask install zoomus

# post install steps
$(brew --prefix)/opt/fzf/install # To install useful key bindings and fuzzy completion:

# Remove outdated versions from the cellar.
brew cleanup
