#!/usr/bin/env bash

# Install command-line tools using Homebrew.

# Make sure we’re using the latest Homebrew.
brew update

# Upgrade any already-installed formulae.
brew upgrade

# Install GNU core utilities (those that come with macOS are outdated).
# Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
brew install coreutils

# Install some other useful utilities like `sponge`.
brew install moreutils

# Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed.
brew install findutils

# Install GNU `sed`, overwriting the built-in `sed`.
brew install gnu-sed --with-default-names

# Install `wget` with IRI support.
brew install wget --with-iri

# Install more recent versions of some macOS tools.
brew install vim --with-override-system-vi
brew install grep
brew install ripgrep
brew install openssh
brew install screen

# Install other useful binaries.
brew install tmux
brew install bat
brew install diff-so-fancy
brew install exa
brew install fzf
brew install git
brew install go
brew install htop
brew install hub
brew install neovim
brew install z

brew install zsh-syntax-highlighting
echo 'source "$HOMEBREW_PREFIX/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"' >> "$HOME/.zshrc"


# install casks (desktop applications)
brew install --cask alfred
brew install --cask bartender
brew install --cask docker
brew install --cask dropbox
brew install --cask firefox
brew install --cask google-chrome
brew install --cask iterm2
brew install --cask alacritty
brew install --cask ngrok
brew install --cask postman
brew install --cask psequel
brew install --cask qlcolorcode
brew install --cask qlimagesize
brew install --cask qlmarkdown
brew install --cask qlstephen
brew install --cask qlvideo
brew install --cask quicklook-csv
brew install --cask quicklook-json
brew install --cask quicklookase
brew install --cask slack
brew install --cask rectangle
brew install --cask spotify
brew install --cask suspicious-package
brew install --cask visual-studio-code
brew install --cask webpquicklook
brew install --cask zoomus

# Fonts
brew tap homebrew/cask-fonts
brew install --cask font-fira-code
brew install --cask font-hack-nerd-font


# post install steps
$(brew --prefix)/opt/fzf/install # To install useful key bindings and fuzzy completion:

# Remove outdated versions from the cellar.
brew cleanup
