#!/usr/bin/env zsh

set -eu

trap 'exit 130' INT

if [[ -z $(command -v bend) ]]; then
	message=$(cat <<-MSG
	  ╔════════════════════════════════╗
  ║                                ║
  ║     This script requires       ║
  ║     HubSpot Asset Bender       ║
  ║                                ║
  ╚════════════════════════════════╝
MSG
)
  echo "$message";
  exit 1;
fi

if [[ -z $(command -v gum) ]]; then
	message=$(cat <<-MSG
	  ╔════════════════════════════════╗
  ║                                ║
  ║     This script requires       ║
  ║  github.com/charmbracelet/gum  ║
  ║                                ║
  ╚════════════════════════════════╝
MSG
)
  echo "$message";
  exit 1;
fi

# Where do you clone your HubSpot projects
HS_PROJECTS_DIR="$HOME/repos"

# ~8gigs (new m1 macbooks have ~64GB of ram so this is pretty reasonable)
NODE_ARGS="NODE_OPTIONS='--max_old_space_size=8192'"

# zsh associative array
# map=("key1" "value1" "key2" "value2")
typeset -A predefined_projects=(
  "payment settings" "settings-ui-payments"
  "product settings" "settings-ui-products products-ui"
  "payments + crm index" "crm-index-ui customer-data-sidebar commerce-sidebar-cards"
)

list_project_directories() {
  command ls -d */ | command cut -f1 -d '/'
}

join_newlines() {
  while read -r lines; do
    command tr '\n' ' ' | command sed 's/ $/\n/'
  done
}

run_with_bend() {
  $("$NODE_ARGS" bend reactor serve "$1")
}

cd $HS_PROJECTS_DIR

# select from predefined_projects to run if we call this script with 'projects'
if [[ $1 == "project" ]]; then
  project_options=""

  for key in ${(k)predefined_projects}; do
    project_options="${project_options}$key\n"
  done

  selected_project=$(echo $project_options | gum choose --height 15)
  printf "running '$NODE_ARGS bend reactor serve %s'" $predefined_projects[$selected_project]
  run_with_bend $predefined_projects[$selected_project]

  # else manually select from all repos
else
  selected_repos=$(list_project_directories | gum choose --no-limit --height 15  | join_newlines)
  printf "running '$NODE_ARGS bend reactor serve %s'" $selected_repos
  run_with_bend $selected_repos
fi

