#!/usr/bin/env bash

# ATLAS_ROOT is the base of this project and provides a safe entry point for other scripts
export ATLAS_ROOT="$HOME/.config/atlas"
export ATLAS_STORAGE_DIR="$HOME/Dropbox"
export ATLAS_NOTES_DIR="$ATLAS_STORAGE_DIR/notes"
export ATLAS_MEDIA_DIR="$ATLAS_STORAGE_DIR/media"
export ATLAS_SCREENSHOT_DIR="$ATLAS_STORAGE_DIR/Screenshots"
export ATLAS_PROJECTS_DIR="$HOME/repos"
export WEBSITE_DIR="$HOME/repos/trevor-atlas"
export BLOG_DIR="$WEBSITE_DIR/posts"
export UNSPLASH_DOWNLOAD_PATH="$WEBSITE_DIR/public/images"

# reduce the number of syscalls
# https://blog.packagecloud.io/set-environment-variable-save-thousands-of-system-calls/
export TZ="America/New_York"
# force ASCII charset for fs searches
# because it's much faster
# https://www.inmotionhosting.com/support/website/speed-up-grep-searches-with-lc-all/
#export LC_ALL=C
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

source "$ATLAS_ROOT/source/install_helpers"
source "$ATLAS_ROOT/source/alias"
source "$ATLAS_ROOT/source/functions"

alias commit="$ATLAS_ROOT/functions/commit"

export EDITOR="nvim"
export VISUAL="code"

install_dotfiles() {
  sh "$ATLAS_ROOT"/install
}

# Above sources are order dependent at the moment so we don't use a loop.
# for f in "$ATLAS_ROOT/source*"; do source $f; done;
set -o vi
