#!/usr/bin/env bash

export ATLAS_ROOT="$HOME/.config/atlas"
export ATLAS_STORAGE_DIR="$HOME/Dropbox"
export ATLAS_NOTES_DIR="$ATLAS_STORAGE_DIR/notes"
export ATLAS_MEDIA_DIR="$ATLAS_STORAGE_DIR/media"
export ATLAS_BLOG_DIR="$ATLAS_STORAGE_DIR/Trevor\’s\ blog"
export ATLAS_SCREENSHOT_DIR="$ATLAS_STORAGE_DIR/Screenshots"
export ATLAS_PROJECTS_DIR="$HOME/projects"

source ${ATLAS_ROOT}/source/install_helpers
source ${ATLAS_ROOT}/source/alias
source ${ATLAS_ROOT}/source/functions

# init vim and tmux config if they don't exist
install_nvim
install_vim
install_tmux
install_i3_preferences
install_i3blocks_preferences
install_spacemacs_preferences
