#!/usr/bin/env bash

alias zshconfig="code $HOME/.zshrc"
alias editconfig="code $ATLAS_ROOT"
alias chromedebug="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222"

# git
# eval "$(hub alias -s)"
alias githistory='git for-each-ref --count=10 --sort=-committerdate refs/heads/ --format="%(refname:short)"'

alias nodescripts="jq '.scripts' package.json"
alias preview="fzf --preview 'bat --color \"always\" {}'"

# add support for ctrl+o to open selected file in VS Code
export FZF_DEFAULT_OPTS=" \
--bind='ctrl-o:execute(code {})+abort' \
--color=bg+:#313244,bg:#1e1e2e,spinner:#f5e0dc,hl:#f38ba8 \
--color=fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc \
--color=marker:#f5e0dc,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8"

if [[ "$(command -v tldr)" ]]; then
  fi

if [[ "$(command -v eza)" ]]; then
  unalias -m 'll'
  unalias -m 'l'
  unalias -m 'la'
  unalias -m 'ls'
  alias ls='eza -G --color auto --icons -a -s type'
  alias ll='eza -l --color always --icons -a -s type'
fi

if [[ "$(command -v bat)" ]]; then
  unalias -m 'cat'
  alias cat='bat -pp'
fi

# utf-8 support
alias tmux='tmux -u'

# Get macOS and Homebrew software updates
alias update="sudo softwareupdate -i -a;\
brew update;\
brew upgrade;\
brew cleanup;"

# Stuff I never really use but cannot delete either because of http://xkcd.com/530/
alias stfu="osascript -e 'set volume output muted true'"
alias pumpitup="osascript -e 'set volume output volume 100'"

# nice ding sound if a script succeeds, error sound if it returns a non-zero exit code
# nice for long running stuff :)
# thing && ding
alias -g ding="osascript -e 'display notification \"Done!\" sound name \"glass\"' || osascript -e 'display notification \"Error!\" sound name \"basso\"'"

alias p=pnpm

alias restartproxy="brew services restart bender-proxy"
alias mvn-verify="mvn clean verify && ding"
