#!/usr/bin/env bash

install_dotfiles_once() {
	# Install homebrew
	/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

	# this is the install script for my dotfiles. it should only be run once
	# setup OSX specific preferences
	source "$ATLAS_ROOT/init/macos"
	. "$ATLAS_ROOT/init/brew"

	# add a .hushlogin to ~ to prevent login messages
	touch "$HOME/.hushlogin"
	mkdir -p "$HOME/src"
	mkdir -p "$HOME/go"
  npm set fund false
  npm set audit false
}

determine_os() {
	unameOut="$(uname -s)"
	case "${unameOut}" in
		Linux*)     machine=linux;;
		Darwin*)    machine=mac;;
		CYGWIN*)    machine=cygwin;;
		MINGW*)     machine=mingw;;
		*)          machine="UNKNOWN:${unameOut}"
	esac
	local __resultvar=$1
	if [[ "$__resultvar" ]]; then
		eval $__resultvar="'${machine}'"
	else
		echo "$machine"
	fi
}

