#!/usr/bin/env bash

install_dotfiles_once() {
	# Install homebrew
	/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

	# this is the install script for my dotfiles. it should only be run once
	# setup OSX specific preferences
	source "$ATLAS_ROOT/init/macos"
	. "$ATLAS_ROOT/init/brew"

	# add a .hushlogin to ~ to prevent login messages
	touch "$HOME/.hushlogin"
	mkdir -p "$HOME/projects"
	mkdir -p "$HOME/go"
}

# update this project with local system changes
atlas_update_from_local() {
	# update spectacle config
	[[ ! -f ${HOME}/Library/Application\ Support/Spectacle ]] && {
		rm "$ATLAS_ROOT/settings/spectacle-app.json";
		cp "$HOME/Library/Application\ Support/Spectacle/Shortcuts.json" ./settings/spectacle-app.json;
	}
}

install_nvim() {
	[[ ! -e ${HOME}/.config/nvim/init.vim && ! -L ${HOME}/.config/nvim/init.vim ]] && {
		ln -sf "$ATLAS_ROOT/settings/vimrc" "$HOME/.config/nvim/init.vim";
		echo "installed nvim config";
	}
}

install_vim() {
	[[ ! -e ${HOME}/.vimrc && ! -L ${HOME}/.vimrc ]] && {
		ln -sf "$ATLAS_ROOT/settings/vimrc" "$HOME/.vimrc";
		echo "installed vim config";
	}
}

install_tmux() {
	[[ ! -d ${HOME}/.tmux/plugins ]] && {
		git clone https://github.com/tmux-plugins/tpm ${HOME}/.tmux/plugins/tpm;
		echo "installed tmux plugin manager"
	}
	[[ ! -e ${HOME}/.tmux.conf && ! -L ${HOME}/.tmux.conf ]] && {
		ln -sf "$ATLAS_ROOT/settings/tmux.conf" "$HOME/.tmux.conf";
		echo "installed tmux config";
	}
}
